import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card } from '../../components/ui/Card';
import { Input } from '../../components/ui/Input';
import { Button } from '../../components/ui/Button';
import { api } from '../../services/api';
import { useAuth } from '../../context/AuthContext';

export const Profile = () => {
  const { user, setUser } = useAuth();
  const navigate = useNavigate();
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(false);

  // Form State
  const [formData, setFormData] = useState({
    name: '',
    mobile: '',
    github_url: '',
    linkedin_url: '',
    skills: ''
  });

  const handleChange = (e) => setFormData(prev => ({ ...prev, [e.target.name]: e.target.value }));

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsLoading(true);
    setError(null);
    setSuccess(false);

    try {
      const skillsArray = formData.skills.split(',').map(s => s.trim()).filter(s => s);
      const payload = {
        // FastAPI UserModel requires these base fields; we provide dummies so validation passes.
        // The backend controller should use the signup_token to retrieve the real values.
        user_id: "dummy_id",
        email: "dummy@example.com",
        username: "dummy_user",
        hashed_password: "dummy_password",
        is_active: true,
        
        name: formData.name,
        mobile: formData.mobile,
        github_url: formData.github_url,
        linkedin_url: formData.linkedin_url,
        skills: skillsArray,
        experiences: [],
        educations: [],
        projects: [],
        leaderships: []
      };

      const signupToken = localStorage.getItem('signup_token');
      
      const createdUser = await api.createUserProfile(payload, signupToken || '');
      
      // Store the real user_id generated by the backend!
      setUser({ id: createdUser.user_id, email: createdUser.email, username: createdUser.username });
      
      setSuccess(true);
      setTimeout(() => navigate('/dashboard'), 1500);
      
    } catch (err) {
      setError(err.message || 'Failed to save profile');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', padding: '40px 20px' }}>
      <h1 style={{ fontSize: '32px', marginBottom: '8px' }}>Your Profile</h1>
      <p style={{ color: 'var(--text-secondary)', marginBottom: '32px' }}>
        This information provides context to the AI Interviewer Planner.
      </p>

      <Card style={{ maxWidth: '100%' }}>
        {error && (
          <div style={{ padding: '12px', backgroundColor: '#FEF2F2', color: '#EF4444', borderRadius: '6px', marginBottom: '16px' }}>
            {error}
          </div>
        )}
        {success && (
          <div style={{ padding: '12px', backgroundColor: '#F0FDF4', color: '#16A34A', borderRadius: '6px', marginBottom: '16px' }}>
            Profile saved successfully! Redirecting...
          </div>
        )}

        <form onSubmit={handleSubmit}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
            <Input label="Full Name" name="name" value={formData.name} onChange={handleChange} required placeholder="John Doe" />
            <Input label="Mobile Number" name="mobile" value={formData.mobile} onChange={handleChange} placeholder="+1 234 567 890" />
            <Input label="GitHub URL" name="github_url" value={formData.github_url} onChange={handleChange} placeholder="https://github.com/..." />
            <Input label="LinkedIn URL" name="linkedin_url" value={formData.linkedin_url} onChange={handleChange} placeholder="https://linkedin.com/in/..." />
          </div>
          
          <div style={{ marginTop: '16px' }}>
            <Input 
              label="Skills (comma separated)" 
              name="skills" 
              value={formData.skills} 
              onChange={handleChange} 
              placeholder="Python, React, System Design, FastAPI" 
              required 
            />
          </div>

          <div style={{ marginTop: '32px', display: 'flex', justifyContent: 'flex-end', gap: '12px' }}>
            <Button type="button" variant="secondary" onClick={() => navigate('/dashboard')}>Cancel</Button>
            <Button type="submit" isLoading={isLoading}>Save Profile</Button>
          </div>
        </form>
      </Card>
    </div>
  );
};

export default Profile;
