"""initial schema

Revision ID: a31bf62b3f72
Revises: 
Create Date: 2026-09-09 20:45:57.702878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a31bf62b3f72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_descriptions',
    sa.Column('jd_id', sa.String(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('job_type', sa.Enum('part_time', 'full_time', name='emptype', native_enum=False), nullable=True),
    sa.Column('loc_type', sa.Enum('remote', 'onsite', name='loctype', native_enum=False), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('min_experience', sa.Float(), nullable=False),
    sa.Column('responsibilities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('required_qualification', sa.String(), nullable=False),
    sa.Column('required_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('jd_id')
    )
    op.create_index(op.f('ix_job_descriptions_jd_id'), 'job_descriptions', ['jd_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('educations',
    sa.Column('education_id', sa.String(), nullable=False),
    sa.Column('institute_name', sa.String(), nullable=False),
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('grade', sa.Float(), nullable=False),
    sa.Column('courses', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('education_id')
    )
    op.create_index(op.f('ix_educations_education_id'), 'educations', ['education_id'], unique=False)
    op.create_table('experiences',
    sa.Column('experience_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('emp_type', sa.Enum('part_time', 'full_time', name='emptype', native_enum=False), nullable=True),
    sa.Column('loc_type', sa.Enum('remote', 'onsite', name='loctype', native_enum=False), nullable=True),
    sa.Column('skills_used', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('experience_id')
    )
    op.create_index(op.f('ix_experiences_experience_id'), 'experiences', ['experience_id'], unique=False)
    op.create_table('leaderships',
    sa.Column('leadership_id', sa.String(), nullable=False),
    sa.Column('committee_name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('skills_used', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('leadership_id')
    )
    op.create_index(op.f('ix_leaderships_leadership_id'), 'leaderships', ['leadership_id'], unique=False)
    op.create_table('projects',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skills_used', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('deployed_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_leaderships_leadership_id'), table_name='leaderships')
    op.drop_table('leaderships')
    op.drop_index(op.f('ix_experiences_experience_id'), table_name='experiences')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_educations_education_id'), table_name='educations')
    op.drop_table('educations')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_job_descriptions_jd_id'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    # ### end Alembic commands ###
